import { IContent } from "../types/IContent";
import { IAssignmentModel } from "@models/statements/assignment/types/IAssignmentModel";
import { IExpressionModel } from "@models/statements/expression/types/IExpressionModel";
import { IVariableModel } from "@models/statements/variable/types/IVariableModel";
import { INewContractModel } from "@models/statements/newcontract/types/INewContractModel";
import { IIfModel } from "@models/statements/if/types/IIfModel";
import { IMethodCallModel } from "@models/statements/methodcall/types/IMethodCallModel";
import { IEventCallModel } from "@models/statements/eventCall/types/IEventCallModel";
import { ICreateContentDTO } from "../types/ICreateContentDTO";
import { IContinueModel } from "@models/statements/continue/types/IContinueModel";
import { IReturnModel } from "@models/statements/return/types/IReturnModel";
import { IAssertModel } from "@models/statements/assert/types/IAssertModel";
import { IBreakModel } from "@models/statements/break/types/IBreakModel";
import { ICatchModel } from "@models/statements/catch/types/ICatchModel";
import { IDoWhileModel } from "@models/statements/dowhile/types/IDoWhileModel";
import { IForModel } from "@models/statements/for/types/IForModel";
import { IMappingModel } from "@models/statements/mapping/types/IMappingModel";
import { IRequireModel } from "@models/statements/require/types/IRequireModel";
import { IRevertModel } from "@models/statements/revert/types/IRevertModel";
import { ITryModel } from "@models/statements/try/types/ITryModel";
import { IWhileModel } from "@models/statements/while/types/IWhileModel";
declare class ContentModel {
    private assertModel;
    private breakModel;
    private catchModel;
    private assignmnetModel;
    private expressionModel;
    private variableModel;
    private newContractModel;
    private ifModel;
    private methodCallModel;
    private eventCallModel;
    private continueModel;
    private doWhileModel;
    private returnModel;
    private forModel;
    private mappingModel;
    private requireModel;
    private revertModel;
    private tryModel;
    private whileModel;
    constructor(assertModel: IAssertModel, breakModel: IBreakModel, catchModel: ICatchModel, assignmnetModel: IAssignmentModel, expressionModel: IExpressionModel, variableModel: IVariableModel, newContractModel: INewContractModel, ifModel: IIfModel, methodCallModel: IMethodCallModel, eventCallModel: IEventCallModel, continueModel: IContinueModel, doWhileModel: IDoWhileModel, returnModel: IReturnModel, forModel: IForModel, mappingModel: IMappingModel, requireModel: IRequireModel, revertModel: IRevertModel, tryModel: ITryModel, whileModel: IWhileModel);
    execute({ stateVars }: ICreateContentDTO): IContent;
}
export default ContentModel;
